// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2W6dIsC7dx1PSNPFByLrZ9yy7r1GT10A',
    appId: '1:925353871907:web:b17665e2e6c0822cd3bf96',
    messagingSenderId: '925353871907',
    projectId: 'chatapp-18b48',
    authDomain: 'chatapp-18b48.firebaseapp.com',
    storageBucket: 'chatapp-18b48.firebasestorage.app',
    measurementId: 'G-M83GR1J6YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAtQUx7oC2XkVH6nbOYXeRD0Vhyed-hvs',
    appId: '1:925353871907:android:6b8795a86155bf44d3bf96',
    messagingSenderId: '925353871907',
    projectId: 'chatapp-18b48',
    storageBucket: 'chatapp-18b48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZICsr5ordvf6pZbnICcY8da4KDrDYnNU',
    appId: '1:925353871907:ios:19e128d0ac07d14dd3bf96',
    messagingSenderId: '925353871907',
    projectId: 'chatapp-18b48',
    storageBucket: 'chatapp-18b48.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZICsr5ordvf6pZbnICcY8da4KDrDYnNU',
    appId: '1:925353871907:ios:19e128d0ac07d14dd3bf96',
    messagingSenderId: '925353871907',
    projectId: 'chatapp-18b48',
    storageBucket: 'chatapp-18b48.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2W6dIsC7dx1PSNPFByLrZ9yy7r1GT10A',
    appId: '1:925353871907:web:0e7a3cfd76bfbbf8d3bf96',
    messagingSenderId: '925353871907',
    projectId: 'chatapp-18b48',
    authDomain: 'chatapp-18b48.firebaseapp.com',
    storageBucket: 'chatapp-18b48.firebasestorage.app',
    measurementId: 'G-V0HZVMRR31',
  );
}
