// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_6_FWgkKI4y4k-EzWEuWHZTIVWlKFfM',
    appId: '1:77296567873:web:0f2d7c34ad856fcd6868c0',
    messagingSenderId: '77296567873',
    projectId: 'chatapp-fd032',
    authDomain: 'chatapp-fd032.firebaseapp.com',
    storageBucket: 'chatapp-fd032.firebasestorage.app',
    measurementId: 'G-V2806FW3XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHO9lZlp9Mdrre4rR_zk0IzuTzRPri0PY',
    appId: '1:77296567873:android:68d73aa445c6b9416868c0',
    messagingSenderId: '77296567873',
    projectId: 'chatapp-fd032',
    storageBucket: 'chatapp-fd032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3HGkNzf3SMc7U3hnF63QSWywutTcbcjU',
    appId: '1:77296567873:ios:6c25273509e4379e6868c0',
    messagingSenderId: '77296567873',
    projectId: 'chatapp-fd032',
    storageBucket: 'chatapp-fd032.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3HGkNzf3SMc7U3hnF63QSWywutTcbcjU',
    appId: '1:77296567873:ios:6c25273509e4379e6868c0',
    messagingSenderId: '77296567873',
    projectId: 'chatapp-fd032',
    storageBucket: 'chatapp-fd032.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_6_FWgkKI4y4k-EzWEuWHZTIVWlKFfM',
    appId: '1:77296567873:web:4a48519bde1fc8926868c0',
    messagingSenderId: '77296567873',
    projectId: 'chatapp-fd032',
    authDomain: 'chatapp-fd032.firebaseapp.com',
    storageBucket: 'chatapp-fd032.firebasestorage.app',
    measurementId: 'G-8PNRPNWTMK',
  );
}
